### ISSUE TITLE
Getting started instructions lacking

### ISSUE THREAD

**Issue by finnbear** [sparkfun/SparkFun_QwiicRF_Library#1]
According to the code example and my experience, you must press and hold the Pair button until paring is complete. This took me a few minutes to figure out because your getting started guide in the Wiki just says "press" the button and then goes on to describe the pairing process.

**Comment by santaimpersonator** [comment]
There should be a prompt in the [example code](https://github.com/sparkfun/SparkFun_QwiicRF_Library/blob/master/examples/Example6-PairingExample/Example6-PairingExample.ino#L115), but I have updated the Wiki to reflect it as well.
